background_opacity 0.9
background_blur 30
# 0.8 80 good combo

cursor_trail 3 
cursor_trail_start_threshold 0
cursor_trail_decay 0.1 0.4
cursor_shape block
cursor_blink true

scrollback_lines 10000

enable_audio_bell     no
bell_on_tab           no

editor /opt/homebrew/bin/nvim

macos_option_as_alt yes
# Make kitty borderless
# "yes" disables round corners and hides the title bar 
# "titlebar-only" leaves round corners but hides title bar
hide_window_decorations titlebar-only

#: The window padding (in pts) (blank area between the text and the
#: window border). A single value sets all four sides. Two values set
#: the vertical and horizontal sides. Three values set top, horizontal
#: and bottom. Four values set top, right, bottom and left.
window_padding_width 0 4

# I'm adding these below the theme in case the theme sets them
# cursor #ffffff
# cursor_text_color #000000

confirm_os_window_close 0

# BEGIN_KITTY_THEM
# Vague
include current-theme.conf
# END_KITTY_THEME


# Fonts

font_size 16
modify_font cell_width 100%
modify_font cell_height -4px
modify_font baseline 3

# BEGIN_KITTY_FONTS
font_family      family='IosevkaTerm Nerd Font Mono' 
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58 IosevkaTerm Nerd Font
symbol_map U+E000-U+E00A IosevkaTerm Nerd Font
symbol_map U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D4 IosevkaTerm Nerd Font
symbol_map U+E200-U+E2A9 IosevkaTerm Nerd Font
symbol_map U+E300-U+E3E3 IosevkaTerm Nerd Font
symbol_map U+E5FA-U+E6B1 IosevkaTerm Nerd Font
symbol_map U+E700-U+E7C5 IosevkaTerm Nerd Font
symbol_map U+EA60-U+EC1E IosevkaTerm Nerd Font
symbol_map U+ED00-U+EFFF IosevkaTerm Nerd Font
symbol_map U+F000-U+F2FF IosevkaTerm Nerd Font
symbol_map U+F0001-U+F1AF0 IosevkaTerm Nerd Font
symbol_map U+F300-U+F372 IosevkaTerm Nerd Font
symbol_map U+F400-U+F533 IosevkaTerm Nerd Font
symbol_map U+F500-U+FD46 IosevkaTerm Nerd Font
symbol_map U+F0000-U+F0FFF IosevkaTerm Nerd Font
